// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_cNRCxl4L27HN55rAug_QxXu0m2FWGEY',
    appId: '1:1050151510536:web:7f88acd869a747d578e7bd',
    messagingSenderId: '1050151510536',
    projectId: 'schedymate',
    authDomain: 'schedymate.firebaseapp.com',
    storageBucket: 'schedymate.firebasestorage.app',
    measurementId: 'G-56S187J4PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtLPYEp5IOsMnvW7MUk9fKRtSVWsMZ2k',
    appId: '1:1050151510536:android:45ff6ae6fb3542c278e7bd',
    messagingSenderId: '1050151510536',
    projectId: 'schedymate',
    storageBucket: 'schedymate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEi1MdPBK0d1S54xyFlHTLoYrYqzHPng',
    appId: '1:1050151510536:ios:1f55dff504f3689278e7bd',
    messagingSenderId: '1050151510536',
    projectId: 'schedymate',
    storageBucket: 'schedymate.firebasestorage.app',
    iosBundleId: 'com.example.schedymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEi1MdPBK0d1S54xyFlHTLoYrYqzHPng',
    appId: '1:1050151510536:ios:1f55dff504f3689278e7bd',
    messagingSenderId: '1050151510536',
    projectId: 'schedymate',
    storageBucket: 'schedymate.firebasestorage.app',
    iosBundleId: 'com.example.schedymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_cNRCxl4L27HN55rAug_QxXu0m2FWGEY',
    appId: '1:1050151510536:web:5f93da1a20ada8d678e7bd',
    messagingSenderId: '1050151510536',
    projectId: 'schedymate',
    authDomain: 'schedymate.firebaseapp.com',
    storageBucket: 'schedymate.firebasestorage.app',
    measurementId: 'G-Y54ZBLPZ9E',
  );
}
